### ISSUE TITLE
error when installing the postgres client

### ISSUE THREAD

**Issue by rjammala** [dmitigr/cefeika#4]
Hi

I get the following error when installing the postgres client:
`
$ sudo make install
[ 33%] Built target os
[ 66%] Built target net
[100%] Built target pgfe
[100%] Built target dmitigr_cefeika_create_resource_destination_dir
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/share/dmitigr_cefeika/LICENSE.txt
-- Installing: /usr/local/share/dmitigr_cefeika/cmake/dmitigr_cefeika.cmake
-- Installing: /usr/local/share/dmitigr_cefeika/cmake/dmitigr_cefeika-config.cmake
-- Installing: /usr/local/include/dmitigr/base.hpp
-- Installing: /usr/local/include/dmitigr/base/version.hpp
-- Installing: /usr/local/include/dmitigr/base/basics.hpp
-- Installing: /usr/local/include/dmitigr/base/debug.hpp
-- Installing: /usr/local/include/dmitigr/base/filesystem.hpp
-- Installing: /usr/local/include/dmitigr/base/macros.hpp
-- Installing: /usr/local/include/dmitigr/base/base.hpp
CMake Error at cmake_install.cmake:75 (file):
  file INSTALL cannot find
  "/home/pgfe/lib/dmitigr/cefeika_header_only.hpp": No such
  file or directory.

Makefile:105: recipe for target 'install' failed
make: *** [install] Error 1
`

**Comment by dmitigr** [comment]
Hi

Sorry for delay! I don't know why, but Github didn't noticed me about this issue! Strange.

The problem is fixed. Thanks for the report!
