### ISSUE TITLE
GET/POST params

### ISSUE THREAD

**Issue by AlexeyRoza** [dmitigr/cefeika#5]
hello.
how to get params of FastCGI request?
REQUEST_URI, HTTP_REFERER, QUERY_STRING, etc

**Comment by dmitigr** [comment]
Hey,

Oh, I'm very sorry, but I didn't noticed this issue! If this question is still actual, currently FastCGI parameters can be read by using methods `Connection::parameter`, for example https://github.com/dmitigr/cefeika/blob/ffc99005699e5e808a3107b55d55821f01ac59ec/fcgi/connection.hpp#L98
